const Portfolio_data = [
    {
        id: 1,
        category: "WEB DEVELOPMENT",
        totalLike: "600",
        title: "Hall's Website Development",
        image: "https://cdn.pixabay.com/photo/2018/05/18/15/30/web-design-3411373_1280.jpg",
        desc1: "Worked as a member of the Frontend Web Development team of Nehru Hall of Residence, IIT Kharagpur",
        desc2: "Added responsive image slider using React JS Hooks and Integrated the auto - playing image carousels and Utilized GitHub as a collaborative platform and learnt the importance of Git in teamwork in development area",
        link: "https://github.com/nehru-website/frontend",
    },
    {
        id: 2,
        category: "WEB DEVELOPMENT",
        totalLike: "750",
        title: "A Real Time Chat App",
        image: "https://images.unsplash.com/photo-1611606063065-ee7946f0787a?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        desc1: "Developed a web app using HTML, CSS, JavaScript, Node.js backend, and Socket.io for real-time communication and Slashed latency by 50% with optimized WebSocket using Socket.io, boosting user experience",
        desc2: "Successfully handled 10,000+ simultaneous connections, showcasing systems' robustness and scalability and Enhanced features for real-time messaging and read receipts resulting in a 30% boost in user satisfaction",
        link: "https://github.com/codersgyan/realtime-chat-app",
    },
    {
        id: 3,
        category: "DATA ANALYTICS",
        totalLike: "630",
        title: "Image Classification",
        image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWFjaGluZSUyMGxlYXJuaW5nfGVufDB8fDB8fHww",
        desc1: "Developed an accurate and efficient model for categorizing dogs and cats using Deep Learning techniques",
        desc2: "Employed Convolutional Neural Networks (CNNs), a powerful deep learning architecture renowned for its effectiveness in image classification tasks and got a validation accuracy of 98% and validation loss of only 0.85",
        link: "https://github.com/shivshankar001/image-classification-using-CNNs",
    },
    {
        id: 4,
        category: "DATA ANALYTICS",
        totalLike: "360",
        title: "Open IIT Data Analytics Competition",
        image: "https://images.unsplash.com/photo-1604948501466-4e9c339b9c24?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29tcGV0aXRpb258ZW58MHx8MHx8fDA%3D",
        desc1: "Collected extensive Shimla tourism data from Google Trends, aggregated 100+ CSV files with diverse keywords",
        desc2: "Discovered that 60% of tourist activity occurs in peak months (April, May, June), informing strategic planning and Mastered time series modeling, excelling with SARIMAX. Fine-tuned parameters for 92% accuracy, RMSE of 12K",
        link: "https://github.com/nehru-website/frontend",
    },
    {
        id: 5,
        category: "WEB DESIGN",
        totalLike: "280",
        title: "Youtube UI Design in Figma",
        image: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2ViJTIwZGVzaWdufGVufDB8fDB8fHww",
        desc1: "Crafted a sleek and user-friendly YouTube UI prototype using Figma, seamlessly blending modern design principles with intuitive navigation.",
        desc2: "The interface showcases a meticulous attention to detail, ensuring a seamless user experience through thoughtfully designed elements, visually appealing aesthetics, and a keen focus on functionality.",
        link: "https://www.figma.com/file/6rotR9xsaXopFTJcRPyDBs/Youtube-UI-Design?type=design&node-id=0%3A1&mode=design&t=LlRvoFHGLMHrGNXx-1",
    },
    {
        id: 6,
        category: "WEB DESIGN",
        totalLike: "690",
        title: "eCommerce UI Design",
        image: "https://plus.unsplash.com/premium_photo-1683133921464-c8c3710fa709?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fG1vYmlsZSUyMGFwcCUyMGRlc2lnbnxlbnwwfHwwfHx8MA%3D%3D",
        desc1: "Discover a seamless and visually captivating eCommerce experience through my meticulously crafted UI design in Figma.",
        desc2: "From engaging product displays to effortless checkout processes, every element is thoughtfully designed to enhance both functionality and aesthetics, ensuring a delightful and efficient shopping experience for users.",
        link: "https://www.figma.com/file/L8M6Ra1lpyn1JItlWprZYa/Shoppe---eCommerce-Clothing-Fashion-Store-Multi-Purpose-UI-Mobile-App-Design-(Community)?type=design&mode=design&t=LlRvoFHGLMHrGNXx-1",
    },
]
export default Portfolio_data